### ISSUE TITLE
Implement smooth scrolling

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#14]

**Comment by inokawa** [comment]
Implementation based on [native behavior option of scrollTo](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo) is probably enough for most cases.

Someone may need customized easing but it should be done outside of this lib with requestAnimationFrame. We have to give an usable example for it.

**Comment by aeharding** [comment]
I'd love to see this! Something I like about Virtuoso is its [`scrollToIndex`](https://virtuoso.dev/scroll-to-index/) function. I make good use of it in Voyager.

https://github.com/inokawa/virtua/assets/2166114/5d35ee5b-c82f-420a-a85d-d7fc492adb12

https://github.com/inokawa/virtua/assets/2166114/91665e2a-c54c-4cc9-8618-099c04119b81

**Comment by morajabi** [comment]
we'd use this as well

**Comment by inokawa** [comment]
I've released initial implementation of smooth scrolling in `0.15.0`.
It may not work well in long scrolling (however as good as react-virtuoso I felt).

I'll try to improve it in the next few releases.
Any feedbacks are welcome!

**Comment by inokawa** [comment]
Much improved in `0.15.1`. Close this issue.
