### ISSUE TITLE
How to add private scrollbar in list?

### ISSUE THREAD

**Issue by NickJiangDev** [inokawa/virtua#154]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by inokawa** [comment]
Hi, what does private scrollbar mean?

**Comment by NickJiangDev** [comment]
@inokawa Hi, when I use VList, I would like to style the scrollbar. However, instead of overriding it with CSS styles, I would like to provide a React component or class to wrap the scroll area. I found that I can only access it through "ref". Is there a way to achieve a similar effect as shown in the image below?
![image](https://github.com/inokawa/virtua/assets/45092189/8afae387-2e8f-42f7-ac7c-730655cb55fd)

**Comment by NickJiangDev** [comment]
> Hi, what does private scrollbar mean?

Hi, when I use VList, I would like to style the scrollbar. However, instead of overriding it with CSS styles, I would like to provide a React component or class to wrap the scroll area. I found that I can only access it through "ref". Is there a way to achieve a similar effect as shown in the image below?
![image](https://github.com/inokawa/virtua/assets/45092189/13094a23-9f9c-4c40-9679-584d77dcb3a2)

**Comment by inokawa** [comment]
If you want to customize component, you can use `components.Root` prop to override default root component.

The default root component is here. Copy paste it and customize by yourself.
https://github.com/inokawa/virtua/blob/609141dadcb7612c7578634b76e876b4f07e0325/src/react/Viewport.tsx#L41-L61

And here is an example overriding root component with `ul`.
https://github.com/inokawa/virtua/blob/609141dadcb7612c7578634b76e876b4f07e0325/stories/basics/VList.stories.tsx#L571-L578

**Comment by NickJiangDev** [comment]
> If you want to customize component, you can use `components.Root` prop to override default root component.
> 
> The default root component is here. Copy paste it and customize by yourself.
> 
> https://github.com/inokawa/virtua/blob/609141dadcb7612c7578634b76e876b4f07e0325/src/react/Viewport.tsx#L41-L61
> 
> And here is an example overriding root component with `ul`.
> 
> https://github.com/inokawa/virtua/blob/609141dadcb7612c7578634b76e876b4f07e0325/stories/basics/VList.stories.tsx#L571-L578
> 
> 
> https://inokawa.github.io/virtua/?path=/story/basics-vlist--ul

Thanks a lot, it works on me.
