### ISSUE TITLE
Add a demo example of react-beautiful-dnd.

### ISSUE THREAD

**Issue by NickJiangDev** [inokawa/virtua#173]
When I want to use react-beautiful-dnd in conjunction with virtua, I'm confused about how to use ref. Could the author provide a specific example?

**Comment by NickJiangDev** [comment]
> I added an example. It was actually bit tricky!
> 
> https://inokawa.github.io/virtua/?path=/story/advanced-with-react-beautiful-dnd--default

Thank you for your time and effort. It's of great value to me, and with your help, I've achieved my goal. I appreciate it very much！

**Comment by mikeyaworski** [comment]
Does anyone have a working solution for when the height of an item is unknown? That example above is good, but it breaks if you don't have equal heights for every item (min height won't work for every element).

**Comment by kuguarpwnz** [comment]
bump

**Comment by kuguarpwnz** [comment]
@inokawa the example got removed. is it still possible to use react-beautiful-dnd with virtua?

**Comment by inokawa** [comment]
Probably possible, but react-beautiful-dnd was deprecated officially. Migrating to pragmatic-dnd is recommended.
https://github.com/atlassian/pragmatic-drag-and-drop

**Comment by kuguarpwnz** [comment]
@inokawa I managed to get it working. I can add an example to storybook if you'd like.
