### ISSUE TITLE
Small layout shift issue when scroll

### ISSUE THREAD

**Issue by reyamir** [inokawa/virtua#206]
Hi, thank for great library

I'm starting integrate virtua to my project, everything is fine but I just have small issue with layout shift. I not sure what cause it, I wonder is it related to this issue? https://github.com/inokawa/virtua/issues/65

https://github.com/inokawa/virtua/assets/123083837/f2241877-569a-419d-8f1b-5d34ddcb7de4

**Comment by reyamir** [comment]
Hi @inokawa , I've tested with virtua v0.9.1 and it totally fine 🤣, so this issue only happen with v0.12.0, it seem strange

**Comment by inokawa** [comment]
Thank you for the additional information.

As I mentioned, I changed range detection algorithm in 0.11.0 and now items at the opposite side of scroll direction will be unmounted while scrolling, which is similar to react-window. 
I suspect this behavior causes the problem.

**Comment by reyamir** [comment]
I've a suggestion, instead of unmount the item, we can replace them with blank div match exact item's height

**Comment by reyamir** [comment]
Hi @inokawa , I've tested with v0.13.0 and it work really well
