### ISSUE TITLE
Paddings not taken into account in reverse mode 

### ISSUE THREAD

**Issue by morajabi** [inokawa/virtua#216]
**Describe the bug**
I set a paddingTop and paddingBottom on `<VList>` in reverse mode. I have a function to scroll to bottom (`scrollToIndex(length - 1, "end")`). Scroll happens but goes to `destinationScrollOffset - paddingTop - paddingBottom` (I mean it doesn't properly scroll to the item)

**To Reproduce**
Steps to reproduce the behavior.
- Enable reverse mode
- Add `style={{ paddingTop: 60 }}` to VList
- Run `scrollToIndex(length - 1)` to scroll to last item
- Notice it stays 60px before to the item.

**Expected behavior**
It should take into account paddings when calculating final scroll position.

**Platform:**

- OS: MacOS
- Browser: Chrome, Safari
- Version of react: 18
- Version of this package: 0.14

**Additional context**
We use Radix scrollview as the root element like the example provided in storybook.
My usecase: I want to add 12px padding bottom to avoid chat messages sticking to my compose input. Also, add 48px paddingTop because I'm placing a blurred header (as the topbar) on top of messages via position absolute and without the padding the top most message will be behind the header element.

P.S. we'd love a new release with latest changes! particularly talking about smooth scrolling & align center :)

**Comment by inokawa** [comment]
Thank you for reporting!
I hope this was fixed in `0.15.0`.

**Comment by morajabi** [comment]
@inokawa 
Thank you! Padding bottom is fixed. However, paddingTop is still not taken into account. 
Say I have 60px of paddingTop, when I scrollToIndex, it is 60px off in v0.15.

**Comment by dena-sohrabi** [comment]
Without paddingTop:
https://github.com/inokawa/virtua/assets/87666169/d32762ee-58f6-46f4-bd46-0490a83a199c

With paddingTop:
https://github.com/inokawa/virtua/assets/87666169/32ccd62f-cb35-4db4-8d3a-b599a5578769

**Comment by inokawa** [comment]
Thank you for the additional information.

I'll try to fix it again but if you hurry using some spacer item like `<div style={{height: 60}}/>` instead of padding may work (Of course you have to add +1 to the destination index though).

**Comment by inokawa** [comment]
Fixed in `0.15.6`.
