### ISSUE TITLE
Provide index for custom item component

### ISSUE THREAD

**Issue by aeharding** [inokawa/virtua#220]
**Is your feature request related to a problem? Please describe.**

`[data-index]` is an attribute Virtuoso provides on each virtual list div, where the value is the index of the item in the array. It would be nice to be able to have data-index on each div, either out of the box or with some customization.

It is helpful to track where you are on the list to perform actions, for example, scrolling to the next virtual list item.

**Describe the solution you'd like**

Something like one of these:

- `CustomItemComponentProps` has `index` (type=number) for user to build custom item with data-index
- [data-index] on each virtual list div, out of the box

**Describe alternatives you've considered**

I can add index inside each item in my implementation. That works, but is tedious and adds another layer of div in my usage.

**Comment by inokawa** [comment]
Hi,
I personally prefer the adding index prop to CustomItemComponentProps approach. And I agree there are no good way to know item index in item wrapper components (some hacks are possible though).

**Comment by inokawa** [comment]
Released in `0.16.5`.
