### ISSUE TITLE
Calling another smooth scroll before previous smooth scroll completes causes strange behavior

### ISSUE THREAD

**Issue by aeharding** [inokawa/virtua#221]
Hello! Thank you for the smooth scrolling support. It works very well, with the only following bug I've found.

**Describe the bug**

Calling another smooth scroll before previous smooth scroll completes causes strange behavior

**To Reproduce**

Call `virtuaRef.scrollToIndex(1, { smooth: true });`, then before smooth scroll is complete, `virtuaRef.scrollToIndex(2, { smooth: true });` then `virtuaRef.scrollToIndex(3, { smooth: true });`

Observe once it scrolls to the third item, smooth scrolling goes back to the second item. It's like there is some strange queuing logic happening that's not being cancelled.

**Expected behavior**

User calling `scrollToIndex` should cancel any previous smooth scroll

**Platform:**

- OS: MacOS
- Browser: Firefox
- Version of react: 18.2.0
- Version of this package: 0.15.0

**Comment by inokawa** [comment]
Could you try `0.15.1`? Thank you for reporting it!.

**Comment by aeharding** [comment]
> Could you try `0.15.1`? Thank you for reporting it!.

Yes this appears to be resolved! However, is it just me, or is there a short 200ms-ish delay on starting a smooth scroll? It makes pressing the scroll button feel a bit laggy in my test. I can make a new issue if that helps.

**Comment by inokawa** [comment]
It's intended one but there may be room for improvement.

Browser's native smooth scrolling can't be stopped during scrolling. So what we can do is measuring all items before scrolling, or scrolling several times like react-virtuoso, (or implement easing with requestAnimationFrame by ourself). Now the first one of them is implemented.

I'm thinking now is cutting down the measurement lags as much as possible and skip some measurements for already measured items, .

**Comment by aeharding** [comment]
I see! For what its worth, this lag doesn't seem to be present in 0.15.0.

**Comment by inokawa** [comment]
@aeharding 
I hope it was resolved in `0.15.3`.
Thank you for your helpful feedback!

**Comment by inokawa** [comment]
Could you raise another issue please? I may not understand the situation correctly.

You said calling scrollToIndex should cancel any previous smooth scroll but should it be changed in some case? Thanks.
