### ISSUE TITLE
Navigate by using keyboard

### ISSUE THREAD

**Issue by reyamir** [inokawa/virtua#227]
Hi, it not really a issue 😅 
I see you mark this issue as completed https://github.com/inokawa/virtua/issues/13 , but I cannnot found document for keyboard

my use case is simple: I want user can navigate item in a list by using keyboard

**Comment by inokawa** [comment]
I added an example for keyboard.
And I had noticed some features are necessary for that usage. So I implemented them in `0.15.5`.
Thank you for raising this issue!
