### ISSUE TITLE
WVList Items are not displayed correctly when restoring scroll position.

### ISSUE THREAD

**Issue by caprolactam** [inokawa/virtua#231]
**Describe the bug**
The items are being rendered, but the screen position is not reflected in WVList Items when scroll position is restored.
That's why Items are not displayed in viewport correctly.

**To Reproduce**
[example in stackblitz.com](https://stackblitz.com/edit/virtua-scroll-restoration-gdun53?file=src%2FApp.tsx)
1. Click "List" button.
2. Scroll down list.
3. Click top-right "prev" button. (equal `History.back()`)
4. Click top-right "next" button. (equal `History.forward()`)
5. Nothing will be displayed in the viewport.

**Expected behavior**
The items display in the viewport correctly.

**Platform:**
- browser: chrome
- virtua: ^0.15.6

**Demonstration**
![screen-capture](https://github.com/inokawa/virtua/assets/85535158/345948f2-8b27-439a-9a82-f12064415a93)

**Comment by inokawa** [comment]
Fixed in `0.15.7`. Thank you for reporting it!
