### ISSUE TITLE
Accept a function instead of rendering all items up front

### ISSUE THREAD

**Issue by zachbryant** [inokawa/virtua#244]
**Is your feature request related to a problem? Please describe.**
My application stutters when element size is very large (1000+).

**Describe the solution you'd like**
Instead of providing elements up front like 
```ts
<VList>
    {rows.map((row, index) => (
        // Some jsx
    ))}
</VList>
```
I'd like to use this pattern:
```ts
<VList items={rows}>
   { (row, index) => renderRow(row, index) }
</VList>
```

**Describe alternatives you've considered**
None

**Additional context**
This is the pattern other libraries also use to avoid the up-front cost of loading items.

**Comment by inokawa** [comment]
Currently it is not planned.
React element is just an object and light enough for most cases.

If React element creation costs, you can use useMemo, memo or other optimization techniques for React.
https://github.com/inokawa/virtua#is-there-any-way-to-improve-performance-further

**Comment by zachbryant** [comment]
The memoization still runs this large object creation though. Even with memoization there's an up-front cost in creating many objects for a complex UI with tens of React elements per row. In my case when there may be 10,000 elements for a user on a slow computer, the performance degradation will lead to a negative experience for my users. Even in a prod build on a fast PC there's a perceptible delay in loading the virtualized list. Up to you to mark it as unplanned but partially defeats the purpose of using a virtualization library.

**Comment by inokawa** [comment]
I think there are 2 major usages of virtualization on browser, heavy and dynamic DOM(with live preview, rich editor, etc) with not so many rows, or relatively light DOM with many rows(10000~).

This library is more focused on the former usage but I agree with that it will have slower start up time compared to the others in the latter usage.

I'll try to add props for it. Thank you for the information!
