### ISSUE TITLE
Consider supporting libraries other than React

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#25]
Vue, Solid, Svelte, Preact and Web Components.

**Comment by legowhales** [comment]
Hey, I'd love to see a Svelte implementation. Is this in the pipeline? How could I help?

**Comment by inokawa** [comment]
Hello.
It's not in progress yet due to priority, however we could maintain if someone contributed rough implementation.

---

For everyone interested in it:

This library is basically constructed with `src/core` (core logics, virtualization state, scroll handler and resize handler) and `src/react` (React components, including markup, styling and React specific implementation).

So we should create `src/svelte` and Svelte component in it if we need Svelte binding. And we have to replace React's APIs connecting to core (`useState`, `useRef`, `useLayoutEffect`...) with Svelte's similar in it. Of course this repo has no setup for typechecking, testing, building and publishing multiple frameworks but we can make it later...

And I think it's ok if VList for Svelte had different API or features from VList for React, because every frameworks expose different APIs and they may not be compatible.

**Comment by inokawa** [comment]
Closing because Vue adapter was released in #282.
If anyone is interested in supporting other frameworks, please raise a independent issue.
