### ISSUE TITLE
Feature Request: Minium Height should match list size rather than fallback to Viewport

### ISSUE THREAD

**Issue by ekm1** [inokawa/virtua#252]
**Is your feature request related to a problem? Please describe.**
Presently, the height is dynamically adjusted to match the viewport when virtual elements are smaller than the viewport itself. However, this occasionally results in undesired empty space between the WVList virtual scroll and the elements beneath it.
https://github.com/inokawa/virtua/blob/c22b81710f36004f1bdd154498dfa16be74640d2/src/core/store.ts#L198
![Screenshot 2023-11-22 at 14 13 56](https://github.com/inokawa/virtua/assets/16984729/3cef1a80-e2a9-4607-998d-39f65532a610)

**Describe the solution you'd like**
If there is an alternative solution maybe no change, but if not maybe a flag to allow the height to skip picking as minimum height the viewport calculation. Or if it sounds sensible no we don't fallback to the viewport at all especially VLists probably should not have to deal with the Viewport height?

**Describe alternatives you've considered**
Probably a custom Root component could do the trick? maybe if accessing the store via ref is possible(not sure haven't tried it)

**Additional context**
Let me know what you think about it, I am looking at highly dynamic list that there are cases that it might be emptier than usual, working with other solutions react-virtuoso/react-virtualized usually the height matches the virtual list total size rather than fallback to the viewport. If there is some technical limitations that I am missing please let me know.

_Note: I can contribute if any code changes are needed_

**Comment by inokawa** [comment]
I think the fallback to viewport size should be removed in WVList, but not in VList.

The fallback was implemented for VList. And it's necessary to keep the size of overflowed div in current design, especially in `reverse: true` mode.
However I didn't check it carefully in WVList. In WVList, viewport size means the window size so it sounds strange to take it as minimum size.

I'm working on another issue now so it may take some time to solve this issue.
Contribution is welcome.

**Comment by ekm1** [comment]
Understood and agreeing, made some changes that would decouple viewport calculation from sizing of WVList.

**Comment by inokawa** [comment]
Released in `0.16.7`.
