### ISSUE TITLE
Add onChangeRange count property back

### ISSUE THREAD

**Issue by feketegy** [inokawa/virtua#256]
The `payload` argument was modified in the `onChangeRange` function and the `count` property was removed in #146 

I can't seem to find a way to replace that property inside the `onChangeRange` function.

**Comment by inokawa** [comment]
Hi, count is just the total length of items so you can get like this:

```tsx
<VList
  onRangeChange={() => {
    const count = data.length;
  }}
  >
  {data.map(d => <Component key={d.key} {...d}/>)}
</VList>
```
