### ISSUE TITLE
Bug: Not all items are shown after prepending (regression in 0.17.3)

### ISSUE THREAD

**Issue by mattwondra** [inokawa/virtua#270]
**Describe the bug**
Sometimes when prepending items, if the new set of items don't fill the viewport then not all items get displayed. Demo:

https://github.com/inokawa/virtua/assets/518059/1d17051f-d235-4df7-923d-32f463e216a1

**To Reproduce**
Steps to reproduce the behavior.

- Start with a set of items that don't fill the viewport
- Use `shift` and add items to the rendered list — but not enough items to fill the viewport
- Sometimes items from the top of the list will be missing and unrendered
- Sometimes items from the bottom of the list will be missing and unrendered
- If you keep prepending to an amount that will cause scrolling, the rendering fixes itself

See demo video above. This can be replicated in production Storybook [using the "Increasing Items" story](https://inokawa.github.io/virtua/?path=/story/basics-vlist--increasing-items).

**Expected behavior**
All items in the set should be visible.

**Platform:**

- OS: MacOS
- Browser: Chrome, Firefox, Safari
- Version of react: 18.2.0
- Version of this package: 0.17.3

**Comment by inokawa** [comment]
Fixed in `0.17.4`.

**Comment by inokawa** [comment]
Your detailed report helped me a lot!
