### ISSUE TITLE
Skeletons infinity loader

### ISSUE THREAD

**Issue by AlanNabiev** [inokawa/virtua#277]
**Is your feature request related to a problem? Please describe.**
I've looked into a lot of libraries for virtual lists, none of them have a ready solution for using a virtual list with infinite scrolling along with skeletons. In the case of the project I'm working on. This is a marketplace where products are presented in 2 variations cards grid and a table list. As well as chat with reverse infinity scrolling with skeletons. If with the list there are still simple solutions with IntersectionObserver Api, then in the case of a grid the setup becomes much more complicated.

**Describe the solution you'd like**
I would like to see a hoc or props that accepts a skeleton component and the ability to specify how many skeletons to show and in which case they no longer need to be shown

**Describe alternatives you've considered**
At the moment we have to do all this manually while supporting infinite scrolling using the Observer intersection API.

Perhaps there is some way to do this, but I did not find an example that suited me in the storybook

I also wanted to express my respect for your work, a very cool library, with quick setup and almost all development cases that need to be covered

**Comment by inokawa** [comment]
Hi, I added basic example for skeleton.
I don't know your app's implementation detail but basically skeletons are items replacing missing data. This list virtualize its children so you can pass skeleton items like normal items.
