### ISSUE TITLE
[Request] Expose cached offsets and heights

### ISSUE THREAD

**Issue by mattwondra** [inokawa/virtua#278]
**Is your feature request related to a problem? Please describe.**
`VListHandle` exposes a `cache` object with really useful details about the virtualized rendering — but unfortunately the keys are obfuscated in production and the `CacheSnapshot` type is opaque. I think there are valid use cases for consumers to access this data and would love to see it exposed in a way I know I can rely on.

One example use case — **true sticky items**.

Virtualization makes `position: sticky` challenging, because the sticky element may get scrolled outside of the rendered range and disappear. The [official Sticky demo](https://inokawa.github.io/virtua/?path=/story/basics-vlist--sticky) skirts around this with pseudo-virtualization — each _group_ is virtualized to ensure that the header will always be rendered. However this creates limitations, such as making it impossible to `scrollToIndex(...)` on any particular row (#241).

However, if we know the virtual position of all the rows, we can actually have true sticky headers by rendering them _next to_ the virtualized items. I've got [an example in this branch](https://github.com/inokawa/virtua/compare/main...mattwondra:virtua:example/true-sticky-headers) — load it up in Storybook and you can see that to the user it looks exactly the same as the official Sticky demo. But now, each row is individually virtualized, meaning we can be more efficient with our overscan and use imperative functions like `scrollToIndex(...)` as expected.

However, this technique relies on grabbing offset data from the cache. I feel hesitant doing that, especially when in production it's clearly not meant for human consumption.

Is there any reason not to expose the inner data of `cache` so we can rely on it? Thanks!

**Describe the solution you'd like**
`VListHandle.cache` should not have its keys obfuscated in production, and should have transparent types and documentation.

**Describe alternatives you've considered**
We can already use the data in `VListHandle.cache` — but since it's not exposed to users I don't know if it's safe to assume it will always be available in that format.

**Comment by mattwondra** [comment]
@inokawa Thanks for the feedback!

Have you verified that a `rangeExtractor`-like solution would actually enable sticky positioning in `virtua`? I've been testing with the current implementation (setting a huge `overscan`) but can't seem to make stickiness work. I think we'd need a custom `Item` because by default it's `position: absolute` which prevents my rendered components from `sticky`-ing to the actual scrolling context. Even with custom `Item`, we have to overwrite position to `sticky` and use `top` for the stuck position — which means we need to adjust the offset with `margin`, or `translateY`, and it seems to bug out whenever I try.

I can kind of fake it by creating a fixed-height container within the custom `Item`, with a much larger-height sticky bounding box that overflows outside of that:

```tsx
const Item = forwardRef<HTMLDivElement, CustomItemComponentProps>(
  ({ children, style, index }, ref): ReactElement => (
    <div ref={ref} style={style}>
      <div style={{ height: 20 }}> {/* The virtualized item will be this height */}
        <div style={{ position: 'absolute', height: 700 }}> {/* The sticky content will scroll within this box */}
          <div style={{ position: 'sticky', top: 0 }}>
            {children}
          </div>
        </div>
      </div>
    </div>
  ),
)
```

In any case, the vanilla version of this still only enables "global stickiness" instead of "ranged stickiness". Meaning we can set a "top: X" but if we don't know the offset of the next sticky header we can't set a "bottom: Y". That means all the sticky items will simple stack on top of one another (like the tanstack example) rather than "moving out of the way for one another" (like the virtua example). If Virtua doesn't offer an API for items to know the position of other items, I suppose the best solution would be inspecting the DOM, and hoping the component is updated when cached positions change to re-calculate the DOM positions.

**Comment by inokawa** [comment]
I checked your branch again and read your comments, I understood what you meant, trickiness of positioning of sticky items and the difference of "global stickiness" and "ranged stickiness".

Probably adding `getItemOffset(index: number): number` like method to `VListHandle` is good for this case. It's just a exposed internal `store._getItemOffset` but it will be much safer than direct access to cache.

**Comment by inokawa** [comment]
`VirtualizerHandle.getItemOffset` was added in `0.27.4`.

**Comment by Azq2** [comment]
@inokawa @mattwondra Thanks, this example really helpful.
I completely copied the sticky date behavior as in Slack/Telegram, without losing virtualization.

Unfortunately, `keepMounted` is not suitable for this, but using `getItemOffset` we were able to get a working solution.

This is a little different from the proposed version, but the general concept is the same.

https://github.com/user-attachments/assets/29d2a781-c478-4fc4-bb8c-7474ba74f22c

1. Inside onScroll (or when data changed) I create a sticky list for the current slice of data:
```ts
const createStickyDates = () => { // called on onScroll or when data changed
  if (!virtualScroll)
    return;

  const start = virtualScroll.findStartIndex();
  const end = virtualScroll.findEndIndex();

  let prevGroup = "";
  const groups: StickyGroup[] = [];
  for (let i = Math.max(0, start - 3); i <= end; i++) {
    const message = chat().messagesList[i];
    const group = `${message.date.getFullYear()}-${message.date.getMonth() + 1}-${message.date.getDate()}`;
    if (group != prevGroup) {
      groups.push({
        title: formatChatDate(message.date),
        offset: virtualScroll.getItemOffset(i),
        size: 0
      });
    }
    groups[groups.length - 1].size += virtualScroll.getItemSize(i);
    prevGroup = group;
  }

  setStickyGroups(groups);
};
```

2. Inside the custom virtual element, I display a placeholder on top of which the date will be displayed.
```ts
const MessageVirtualItem: ParentComponent<CustomItemComponentProps> = (props) => {
  const isFirstMessageOnDate = createMemo(() => {
    const message = chat().messagesList[props.index];
    const prevMessage = chat().messagesList[props.index - 1];
    return !prevMessage || isDateChanged(message.date, prevMessage.date);
  });
  return (
    <div ref={props.ref} style={props.style}>
      <Show when={isFirstMessageOnDate()}>
        <div class="messages-list__date-placeholder"></div> {/* <--- look this */}
      </Show>
      {props.children}
      <Show when={props.index < chat().messagesList.length - 1}>
        <div class="messages-list__gap"></div>
      </Show>
    </div>
  );
};
```

3. Then I do something this:
```ts
return (
  <div class="messages-list" ref={scrollTarget}>
    <DialogNavButton
      visible={showNavButton()}
      onClick={handleNavButton}
    />

    <div ref={scrollViewport}>
      <div class="messages-list__reverse">
        <div style={{ position: "relative" }}>
          <Index each={stickyGroups()}>{(group) =>
            <div
              class="sticky-group"
              style={{
                top: group().offset + "px",
                height: group().size + "px",
              }}
            >
              <div class="sticky-group__title">{group().title}</div>
            </div>
          }</Index>
          <Virtualizer
            ref={(ref) => ref && handleVirtualScrollInit(ref)}
            overscan={10}
            scrollRef={scrollViewport}
            onScroll={handleScroll}
            onScrollEnd={handleScrollEnd}
            data={chat().messagesList}
            shift={chat().shift}
            item={MessageVirtualItem}
          >{(message, index) =>
            <MessageItem
              chat={chat()}
              message={message}
              index={index()}
            />
          }</Virtualizer>
        </div>
      </div>
    </div>
  </div>
);
```

4. And the CSS looks something like this:
```scss
$messages-gap: 10px;

.sticky-group {
  position: absolute;
  width: 100%;
  left: 0;
  visibility: visible;
  z-index: 1;
  box-sizing: border-box;
  padding-bottom: $messages-gap;

  &__title {
    position: sticky;
    display: inline-block;
    z-index: 1;
    top: 0;
    left: 50%;
    transform: translateX(-50%);
    background: rgba(0, 0, 0, 0.3);
    color: #fff;
    border-radius: 30px;
    padding: 4px 8px;
    font-size: 14px;
    line-height: 16px;
    font-weight: 500;
  }
}

.messages-list {
  position: relative;
  height: var(--content-height);
  padding: $messages-gap;
  box-sizing: border-box;

  &__reverse {
    visibility: hidden;
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
    min-height: 100%;
  }

  &__date-placeholder {
    padding-bottom: calc(24px + $messages-gap); // sticky date height + gap
  }

  &__gap {
    padding-bottom: $messages-gap;
  }
}
```

P.S. This is an implementation for SolidJS, but for React everything will equal.
I can't share all code at the moment, but I promise I'll make an example for storybook.
