### ISSUE TITLE
[feature] Virtua for vue3

### ISSUE THREAD

**Issue by AlanNabiev** [inokawa/virtua#282]
An excellent library that is sorely lacking for Vue3.

I would like to help with writing a package for Vue3. Tell me, is work already being done in this direction? And how could I help?

I would like to discuss the architecture for implementing other framework solutions and help.

**Comment by NovaAstra** [comment]
I'm looking forward to the vue3 version of virtua

**Comment by inokawa** [comment]
A barebone implementation for Vue was released in `0.18.0`. Feedback is welcome.
