### ISSUE TITLE
Need ability to align items in the end when they are smaller than viewport height

### ISSUE THREAD

**Issue by m-mityureva** [inokawa/virtua#283]
**Is your feature request related to a problem? Please describe.**

I need to align items in the end in case if total items height is less than viewport height. Like on the screenshot
<img width="595" alt="image" src="https://github.com/inokawa/virtua/assets/37265338/7ae4be4e-b330-4d9c-af2f-5fdb478130b5">

**Describe the solution you'd like**

I could achieve it via custom styles if minimum height matched list size as it was proposed here https://github.com/inokawa/virtua/issues/252

**Describe alternatives you've considered**

I'm not sure I could handle it on my side even if `getTotalSize` was available via ref.  Because it should react on any resizes.

**Comment by inokawa** [comment]
Hi, it's not well documented but you can achieve it with `reverse: true`!
