### ISSUE TITLE
Add Svelte VList

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#323]

**Comment by say16** [comment]
great.

**Comment by inokawa** [comment]
One difficult point is that we should support svelte 4 or not.
Supporting only >=5 is easier because many breaking changes will likely happen on v5.

**Comment by moaali** [comment]
@inokawa IMO, development should be for **v4**, as v5 should be backward compatible and the migration requires minimal changes to the current code bases as stated on the preview page https://svelte-5-preview.vercel.app/docs/breaking-changes
