### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "p". Expected Object, got Function 

### ISSUE THREAD

**Issue by MstrVLT** [inokawa/virtua#337]
https://github.com/inokawa/virtua/blob/f11f470ee16491c86fab786db779179f8c4ed7c4/src/vue/ListItem.tsx#L12

To 
`    _resizer: { type: Function as PropType<ItemResizeObserver>, required: true },`

**Comment by inokawa** [comment]
@MstrVLT 
Hi, thank you for your report. 
Could you make a PR for it? If you don't have time, I'll take this fix in a few days.

**Comment by MstrVLT** [comment]
Sure
https://github.com/inokawa/virtua/pull/338

**Comment by inokawa** [comment]
Released in `0.21.1`. Thanks!
