### ISSUE TITLE
Unexpected behavior when jumping to the first item of reversed infinite list

### ISSUE THREAD

**Issue by m-mityureva** [inokawa/virtua#357]
**Describe the bug**
When I jump to the first item of reversed infinite list using `scrollToIndex`, scrollbar stays at the top and it keeps loading more and more items. It's not reproduced if I increase a new page loading delay.
Video attached:
https://github.com/inokawa/virtua/assets/37265338/47cfab6b-058b-4449-8df9-620d0356fd93

**To Reproduce**
Link to the sandbox https://codesandbox.io/p/sandbox/virtua-reverse-infinite-scroll-74jnpn

**Expected behavior**
Scrollbar position is updated correctly as soon as new items are prepended, no matter if there is a delay or not

**Platform:**
- Version of this package: 0.23.0
- Version of framework: react 18.2.0

**Comment by m-mityureva** [comment]
Sorry, now it should be available

**Comment by inokawa** [comment]
Prepending during scrolling to was not expected. It might be better to fix the logic of imperative scrolling.

**Comment by m-mityureva** [comment]
For some reason codesandbox doesn't see the new package version, but I ran the same example in storybook locally (pulled the latest changes), and seems like it's still reproduced

**Comment by inokawa** [comment]
You should replace `scrollToIndex(0)` with `scrollTo(0)`, otherwise it will be reproduced.

**Comment by m-mityureva** [comment]
I also managed to reproduce it with `scrollToIndex(1)`, probably the main condition - close to top enough to trigger next page loading. I don't think I can use `scrollTo(0)` instead of `scrollToIndex(1)`

**Comment by inokawa** [comment]
#346 is a problem with prepending during native scroll. This issue is a problem with prepending during imperative scroll.
They are similar issue but the solution can be a bit different.

**Comment by m-mityureva** [comment]
Does it make sense to reopen this issue? Since it's reproduced not only for index=0?

**Comment by m-mityureva** [comment]
Thanks, I will try using scrollTo + loading delay (only for jumping) for now

**Comment by inokawa** [comment]
Probably fixed in `0.23.3`.

**Comment by m-mityureva** [comment]
@inokawa it seem to be fixed, thanks! Your lib is awesome 🤩
