### ISSUE TITLE
Add grouped mode support

### ISSUE THREAD

**Issue by mariia-mitiureva** [inokawa/virtua#370]
**Is your feature request related to a problem? Please describe.**
Hi, it's me again :) It would be great to have some component that behaves like [the storybook Sticky example](https://inokawa.github.io/virtua/?path=/story/basics-vlist--sticky). But in this example virtual list item is the whole group, which means that I cannot scroll to any item inside a group using `scrollToIndex`. Also if there are many items in one group, it will break optimisation - all group items will be rendered.

**Describe the solution you'd like**
For references: [virtuoso grouped mode](https://virtuoso.dev/grouped-numbers/), how Slack groups messages by date -
https://github.com/inokawa/virtua/assets/37265338/e39c7385-9183-42a3-86cd-96e8f2415b3b

**Describe alternatives you've considered**
I was thinking if it's possible to implement similar behavior on my side using VList, but no solution yet

**Comment by inokawa** [comment]
Yes, sticky item feature was asked several times, and there are no good way to do it without fork for now.

It will be implemented as a feature like `rangeExtractor`(https://github.com/inokawa/virtua/issues/278#issuecomment-1847031243) or `VListHandle.getItemOffset`(https://github.com/inokawa/virtua/issues/278#issuecomment-1848208963), but not yet decided.

**Comment by morajabi** [comment]
Will this support 2 levels of nesting of sections? eg. I'd like to group messages per day and per sender

**Comment by inokawa** [comment]
For now, what I'm planning for the first release is to add a functionality to keep items offscreen at any indexes.
With `position: sticky` styling by user, it will work as sticky header of grouped items.

I'm not familiar to nested sticky styling. I think it depends on markup but perhaps it will work also.

**Comment by hamaddo** [comment]
any updates?

**Comment by inokawa** [comment]
I recreated sticky example based on `keepMounted` feature added in #429 .
https://inokawa.github.io/virtua/?path=/story/advanced-sticky-group--default
https://github.com/inokawa/virtua/blob/main/stories/react/advanced/Sticky%20Group.stories.tsx

Closing this issue because it will solve the problem originally raised. It will support `GroupedVirtuoso`-like "global stickiness" but I'm not sure for "ranged stickiness"(explained in #278).
Thank you!
