### ISSUE TITLE
Add scrollRef prop to Vue Virtualizer

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#379]
It's necessary for complex markup.
Just port React implementation.

**Comment by billouboq** [comment]
is scrollRef working on react ? did not found the implementation and was not being able to make it work with a list that has header before the actual list and scroll is done by some parent view

**Comment by inokawa** [comment]
@billouboq 
React's implementation is here.
https://github.com/inokawa/virtua/blob/d6faef0012e5089e896a9a7a680d99874b8a60a6/src/react/Virtualizer.tsx#L262-L267

I just tried to implement it for Vue in https://github.com/inokawa/virtua/pull/393. However, it is not working correctly at the moment. I'm not an expert of Vue so maybe something is wrong.
