### ISSUE TITLE
Issue with smooth scroll during item resize after upgrading to 0.27

### ISSUE THREAD

**Issue by aeharding** [inokawa/virtua#380]
**Describe the bug**

When I change an item height and smooth scroll to its index at the same time, Virtua is no longer scrolling to the correct position. This was working in 0.26 so something has changed.

**To Reproduce**

1. Pull down [this storybook file](https://github.com/aeharding/virtua/commit/be01be5e99fb7b4861d8d889dc7e2260fe92fc79) and open storybook -> Advanced: Resize and scroll
2. Scroll so item top edge is just outside viewport
3. Tap "Resize and Smooth Scroll"
4. Observe scroll is not smooth and does not jump to correct location and scroll sometimes does not occur (see after video).
5. Additionally, in Safari there are some new glitches in 0.27.0 where user scroll after doing the resize + smooth scroll can cause items to hide/not render until the next user scroll. I haven't created a reproduction for this yet, but it happens in [Voyager](https://github.com/aeharding/voyager) with the swipe to collapse with virtua 0.27.0. I can validate any potential fix to see if it is resolved :)

**Expected behavior**

0.26.0 behavior.

**Platform:**

I've tested:

- OS: [Windows, MacOS, Linux, Android, iOS] iOS, MacOS
- Browser: [Chrome, Firefox, Safari, Edge] Firefox, Safari
- Version of this package: [x.x.x] 0.27.0
- Version of framework: [react, vue, solid-js] react 18.2.0

**Additional context**

I am happy to make a PR for the storybook reproduction, if it would help.

| Before (0.26.0 - good)  | After (0.27.0 - bad)  |
|---|---|
| <video src="https://github.com/inokawa/virtua/assets/2166114/ec7617dd-d63c-410a-85c1-3d417a74051f">  | <video src="https://github.com/inokawa/virtua/assets/2166114/0a7f0b16-137f-4e70-9b9a-7d080e451dcb"> |

**Comment by inokawa** [comment]
@aeharding 
> I am happy to make a PR for the storybook reproduction, if it would help.

Thanks! Could you make a PR for that?
https://inokawa.github.io/virtua/?path=/story/basics-vlist--with-state is a similar story but it seems like it's not enough.

**Comment by inokawa** [comment]
At least the issue except 5 should be fixed in `0.27.1`.
Feel free to reopen or open another issue if you noticed something.

**Comment by inokawa** [comment]
I found that smooth scrolling + resizing to smaller size can cause blank sometimes.
It was fixed in `0.27.2`.

**Comment by aeharding** [comment]
Thank you! That is working perfect :)
