### ISSUE TITLE
Unstable position when resizing item after upgrading to 0.27.0

### ISSUE THREAD

**Issue by aeharding** [inokawa/virtua#385]
**Describe the bug**

Hi! This is the last 0.27.x bug. I'm sorry I didn't report at the same time as the other bug. I think maybe they are related, or at least the cause is similar?

Essentially, when resizing items, if the top of the item is outside the viewport, the item position is unstable.

**To Reproduce**

 1. Have a single, tall Virtua item that can collapse `<div>`s within it.
 2. Collapse those `<div>`s **while the top of the Virtua item is outside the top of the viewport** (important: this bug does not occur unless the top of the containing Virtua item is outside the viewport).
 3. Observe that the collapse is not stable. Collapsing and expanding over and over moves the container around. Additionally, sometimes the item moves up, sometimes down, it is unpredictable.

**Expected behavior**

Virtua item position remains fixed. The `<div>`s expand downwards (see video) as per Virtua < 0.27.0.

**Platform:**

- OS: [Windows, MacOS, Linux, Android, iOS] iOS, MacOS
- Browser: [Chrome, Firefox, Safari, Edge] Firefox Safari
- Version of this package: [x.x.x] 0.27.2
- Version of framework: [react, vue, solid-js] react 18.2

**Additional context**

Here is my reproduction example:

I have pushed to a PR here: https://github.com/inokawa/virtua/pull/384

|  Before (Virtua 0.26.0) | After (Virtua 0.27.2)  |
|---|---|
|  <video src="https://github.com/inokawa/virtua/assets/2166114/cff9d391-f2b1-4035-a4bd-5d1c38315c49"> |  <video src="https://github.com/inokawa/virtua/assets/2166114/d5d6a059-e5b0-4c77-bbbc-a44588f079ec"> |

Here is an example of the problem in Voyager (Voyager only virtualizes the root comments, so items within the root comment are seen as one "item" to Virtua):

|  Before (Virtua 0.26.0) | After (Virtua 0.27.2)  |
|---|---|
| <video src="https://github.com/inokawa/virtua/assets/2166114/2e30a320-d511-4ce0-9fc1-80a21d4aaf8a">  |  <video src="https://github.com/inokawa/virtua/assets/2166114/e6badbd9-d5de-4da9-bf8a-f187be1745ba"> |

**Comment by inokawa** [comment]
Probably fixed in `0.27.3`.

**Comment by aeharding** [comment]
Hi @inokawa 

Thank you, it is working better, but I am still noticing some strange behavior. See the following video, where the last item I expand, expands upward, instead of downward like it did <0.27.

I can try creating a story book for this later if you would like!


https://github.com/inokawa/virtua/assets/2166114/421bc883-dce0-450a-baa7-d499d6e59225
