### ISSUE TITLE
Any way to scrollBy with smooth option?

### ISSUE THREAD

**Issue by vu0tran** [inokawa/virtua#387]
I see the interface scrollToIndex takes optional parameter "smooth" but I'm not seeing the same interface for scrollBy(offset). Can someone help confirm? Thanks

**Comment by inokawa** [comment]
Hi, it's not implemented yet because it wasn't requested until now.
What situations do you need it for?

**Comment by vu0tran** [comment]
specifically for mobile. When the keyboard comes up, I want to smoothly scroll the scrollview down by Y pixels to match the keyboard resize :)

**Comment by inokawa** [comment]
Thanks!

As a workaround, you can use native `scrollBy` instead of VList's scrollBy like:

```tsx
useEffect(() => {
  const handle = document.querySelector('.handle');
  handle.scrollBy({ top: 1000, behavior: 'smooth' });
}, [])

<VList className="handle">
  {...}
</VList>
```

or with Virtualizer:

```tsx
const ref = useRef<HTMLDivElement>(null);

useEffect(() => {
  ref.current.scrollBy({ top: 1000, behavior: 'smooth' });
}, [])

<div style={{ overflowY: 'auto'}} ref={ref}>
  <Virtualizer>
    {...}
  </Virtualizer>
</div>
```

It seems that correct usecase so maybe we should add smooth option to VList's scrollBy.

**Comment by vu0tran** [comment]
sorry for the late follow up but this works, thank you! Closing
