### ISSUE TITLE
shift not working correctly when horizontal is true

### ISSUE THREAD

**Issue by tonymontana97** [inokawa/virtua#412]
**Is your feature request related to a problem? Please describe.**
We use virtua for our horizontal infinity virtualised list, initial position always middle of list, when user reach start of virtualised list, we prepend new items, but after prepending with enabled shift, scroll position restoring in middle of list and it's visible for eyes.

**Describe the solution you'd like**
Looks like shifting not working for horizontal prepending of elements, I think we can make next: when  shifting is true and horizontal scroll enabled, then after prepending of new items restore scroll position on difference between scrollSize, I have made this by myself, but cool if you implement it from box 

**Additional context**
This library if perfect solution for our application. We have try more than 5 different libraries including react-window, but virtua is the best, really. Thanks you!

**Comment by inokawa** [comment]
Hi, thank you for trying my lib!

I've made a horizontal reverse infinite scrollable list in my local with virtua `0.29.0` and it works fine.
Could you make a minimal reproduction, or give me more detailed information of your situation?

https://github.com/inokawa/virtua/assets/48897392/2caf9214-10a8-485c-afa6-b5801dfb0f98

**Comment by tonymontana97** [comment]
@inokawa Sorry, issue was on our side, also we replace Virtualizer with VList, VList has restoration.

Thanks!
