### ISSUE TITLE
Support Web Components

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#419]
### Discussed in https://github.com/inokawa/virtua/discussions/418

<div type='discussions-op-text'>

<sup>Originally posted by **clibu** March 25, 2024</sup>
I'd like to use virtua with [Lit Element](https://lit.dev/) I've read through the docs for use with React, Vue & Solid but can't see how I can adapt any of these examples to work with Lit. Lit is based around Web Components, so having virtua support Lit & therefore Web components would be great. 

Thanks for all your work on virtua.</div>

**Comment by clibu** [comment]
+1

**Comment by inokawa** [comment]
I'm closing this issue because I don't have enough time to investigate what is the best way for Lit and Web Components, and create adapter and maintain it.

Instead, we'll publish core modules in #428 . If someone created a library for Lit or Web Components with it, we can recommend it in this repository.
