### ISSUE TITLE
Cannot find module 'virtua/solid'

### ISSUE THREAD

**Issue by imascha** [inokawa/virtua#420]
**Describe the bug**
I am trying to follow the solid.js getting started in the inside the readme. But i am not able to import `VList` from `virtua/solid`. 
When i use the `VList` from `virtua` i get the following browser error: `Uncaught Error: Could not resolve "react/jsx-runtime" imported by virtua. Is it installed?` 
When i use `VList` from `virtua/lib/solid` i get the following node error: `Internal server error: Missing "./lib/solid" specifier in "virtua" package` 

**To Reproduce**
1. Created a new solid.js project: `npx degit solidjs/templates/ts my-app`
2. Installed dependencies: `npm install`
3. Installed the library: `npm install virtua`
4. Copied the getting started Example inside the `App.tsx` 

**Platform:**
- OS: Windows
- Browser: Chrome
- Version of this package: 0.29.1
- Version of framework: solid-js 1.8.11

**Additional context**
Am i doing something incorrectly or is something broken?

**Comment by inokawa** [comment]
If you have tsconfig in the template, changing `moduleResolution: "node" to `moduleResolution: "bundler" may solve the problem because `moduleResolution: "node" can't resolve exports of package.json.
https://github.com/solidjs/templates/blob/924ee8359dc908c3ca3bd622c0c32dd2d666c78e/ts/tsconfig.json#L6

**Comment by Azq2** [comment]
But why? All other packages works fine with any type of moduleResolution....

**Comment by inokawa** [comment]
That's because virtua uses `exports` field of package.json for entry point for frameworks other than React, which is not supported by `moduleResolution: node` (Node.js 12 compatible resolution).
https://github.com/inokawa/virtua/blob/4ff43ff0061bd5f6c48bae0888631fa35b25887a/package.json#L20-L25
