### ISSUE TITLE
`NaN` is an invalid value for the `top` css style property. 

### ISSUE THREAD

**Issue by meotimdihia** [inokawa/virtua#441]
**Describe the bug**
The bug happen with virtua > 0.27.4 ( the bug doesn't happen on <= 0.27.4)

https://github.com/inokawa/virtua/assets/300961/3b895926-9220-4d43-91b6-77adc760b947

 Make the browser not responsive and the console output the warning: \`NaN\` is an invalid value for the \`top\` css style property. 

**To Reproduce**
[Steps to reproduce the behavior.](https://stackblitz.com/edit/stackblitz-starters-zqsq8z?)
        Step to reproduce the bug:
        1. Click the link "Scroll Restoration Page"
        2. CLick the button "Make List Smaller"
        3. Click the link "Home"
        4.Click the link "Scroll Restoration Page"
        
**Expected behavior**

**Platform:**

- OS: Any
- Browser: Chrome
- Version of this package:  virtua > ^0.27.4 ( the bug doesn't happen on 0.27.4(
- Version of framework: react

**Comment by inokawa** [comment]
This example seems to be working as expected.
If you restore the scroll position, also you have to restore the items (that is not documented though).
I refactored the internal cache at 0.28.0. The example might work with older version but it's unexpected behavior.

**Comment by inokawa** [comment]
...or maybe we should accept cache with shorter length as a special cache. I would be safer.

**Comment by inokawa** [comment]
Should be fixed in `0.30.5`.
