### ISSUE TITLE
Scroll to bottom doesn't work correctly in inactive tab

### ISSUE THREAD

**Issue by mariia-mitiureva** [inokawa/virtua#450]
**Describe the bug**
Scroll to bottom doesn't work correctly in inactive tab - [video](https://github.com/inokawa/virtua/assets/37265338/7d04b02b-6fee-466f-bf7f-27a5171665d0)

**To Reproduce**
1. Bookmark this storybook page https://inokawa.github.io/virtua/?path=/story/advanced-chat--default
2. Open it in a new tab (tab should be inactive while page is loading)
3. Go to that tab
Result: list is not scrolled to the bottom

**Expected behavior**
Scroll to bottom works correctly in inactive tab

**Platform:**
- Browser:  reproduced in Chrome and Edge, _not_ reproduced in Safari
- Version of this package: 0.31.0

**Comment by inokawa** [comment]
It seems that ResizeObserver doesn't fire on non-active window in some browsers. Scheduled imperative scrolling waits for the resize events so timeout will happen.

As a workaround, you may be able to wait for the tab to be active with `document.addEventListener("visibilitychange", callback)` and then call imperative scroll. Or maybe we should implement similar logic inside virtua.

**Comment by mariia-mitiureva** [comment]
Maybe support of initial scroll position (https://github.com/inokawa/virtua/issues/415, https://github.com/inokawa/virtua/pull/422) could solve the issue?
In the real project, where components are heavier than in storybook, this initial scroll to bottom sometimes is noticeable for user.

**Comment by inokawa** [comment]
#415 will not solve this issue, because #415 is just an unimplemented feature but this issue is a browser problem.

**Comment by mariia-mitiureva** [comment]
I understand. I guessed that if I had ability to set the initial scroll position without extra render cycle, maybe it wouldn't need to wait for resize events and the problem would go away.

**Comment by mariia-mitiureva** [comment]
A similar issue happens in safari if I switch pages back and forward by swiping. @inokawa do you have any idea why it can happen and how to fix it?

https://github.com/inokawa/virtua/assets/37265338/beb6fbfe-309d-4ac3-9967-09566fcca6a4

**Comment by inokawa** [comment]
Thank you for the report!
In the situation, window is always active but scrollTo has timed out earlier than the initial resize. Maybe we should add a logic to wait for the initial resize and then trigger the scroll only on mount.

**Comment by inokawa** [comment]
Fixed in `0.33.3`.
