### ISSUE TITLE
Infinite reverse scroll breaks on Safari

### ISSUE THREAD

**Issue by XantreDev** [inokawa/virtua#473]
**Describe the bug**
Infinite reverse scroll breaks on Safari. It only updates layout when scroll is released for more couple hundreds of milliseconds

**To Reproduce**
Scroll to top and add items on top of the list when range is near first element
https://github.com/yokenfoundation/bilft/blob/992177dbabb21df29ee312d2aef0fd18659019e6/source/features/CommentsPage/CommentsPage.tsx#L770-L781

https://github.com/user-attachments/assets/66e979b9-e3a4-4a99-ac70-9ad219a017a1

**Expected behavior**
It must update list while scrolling

**Platform:**

- OS: iOS
- Browser: Safari
- Version of this package: 0.33.3
- Version of framework: solid-js [1.8.17]

**Additional context**
Telegram mini app safari

**Comment by inokawa** [comment]
https://github.com/inokawa/virtua/issues/403#issuecomment-1978126177
