### ISSUE TITLE
Failed to load url ../core/utils

### ISSUE THREAD

**Issue by adjsky** [inokawa/virtua#506]
**Describe the bug**
Vite fails with `Failed to load url ../core/utils (resolved id: ../core/utils)` error.

**To Reproduce**
Just import `VList` from `virtua/svelte` or go to [StackBlitz](https://stackblitz.com/edit/vitejs-vite-7y3ywo?file=src%2FApp.svelte).

**Expected behavior**
Vite doesn't fail.

**Platform:**

- OS: doesn't matter
- Browser: doesn't matter
- Version of this package: 0.34.1
- Version of framework: svelte 4.2.19

**Additional context**
Seems like the `lib/core` directory contains only type definitions in the published files, but `lib/svelte/utils` tries to import `.js` file, which doesn't exist (https://www.npmjs.com/package/virtua/v/0.34.1?activeTab=code).

**Comment by inokawa** [comment]
Could you try `0.34.2`? Thanks!

**Comment by adjsky** [comment]
Yep, everything works great in 0.34.2. Thank you!
