### ISSUE TITLE
virtua/svelte: onscroll does not differentiate between vertical and horizontal scroll event

### ISSUE THREAD

**Issue by Karakatiza666** [inokawa/virtua#533]
When using VList for a vertical list, when doing horizontal scroll onscroll callback is fired with effectively `scrollTop` value. Ideally, either
- the `onscroll` callback would provide `{scrollLeft: number, scrollTop: number, deltaX: number, deltaY: number}`, or
- expose `onscrollx` and `onscrolly` callbacks that each have `(offset: number, delta: number)`

**Comment by inokawa** [comment]
It was not exposed because it's not related to virtualization and accessing scrollTop/scrollLeft excessively can degrade perf.

If you want scrollLeft while vertical scrolling, use `Virtualizer`, like:

```svelte
<div style="overflow: auto; width:XXpx; height:XXpx" onscroll={(e)=>{ e.target.scrollLeft /* access scrollLeft*/ }}>
  <Virtualzer>
    ...
  </Virtualizer>
</div>
```

**Comment by Karakatiza666** [comment]
I''ll try Virtualizer, thanks! My main goal is to run some code on vertical scroll, but not horizontal scroll

**Comment by Karakatiza666** [comment]
@inokawa still, it is confusing that when you use vertical VList and do a horizontal scroll `onscroll` still gets called with `scrollTop` value

**Comment by inokawa** [comment]
Thanks for the feedback. I updated the docs a bit.
