### ISSUE TITLE
Appended items in the list appear only after scrolling in Vue/Solid/Svelte

### ISSUE THREAD

**Issue by Karosmiy** [inokawa/virtua#552]
**Describe the bug**
appended items appears only after scrolling 
https://github.com/user-attachments/assets/b8821b92-e320-4256-aeb4-1c1b16c01f38

**To Reproduce**
1. go to https://inokawa.github.io/virtua/?path=/story/svelte_vlist--controls
2. scrollToIndex 999
3. click append button
4. items appended after scrolling

**Expected behavior**
New items should appear in the list immediately as they are added, without requiring the user to scroll.

**Additional context**
if `shift` property is true, items are inserted immediatly.

**Comment by Karosmiy** [comment]
https://github.com/inokawa/virtua/blob/1016af70124d217e12571c78d3fb7bc2ab2d229a/src/core/store.ts#L399-L407
Maybe it makes sense to update the variable mutated here

**Comment by Karosmiy** [comment]
Also we can trigger update of range variable by adding data.length
`let range = $derived(data.length && rerender && virtualizer[GET_RANGE]());`

**Comment by Karosmiy** [comment]
> Also we can trigger update of range variable by adding data.length `let range = $derived(data.length && rerender && virtualizer[GET_RANGE]());`

@inokawa what do you think of this solution?

**Comment by inokawa** [comment]
It looks ok but not sure it works.
