### ISSUE TITLE
Implement Table component

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#7]

**Comment by inokawa** [comment]
Closed due to no strong need to implement.

**Comment by Monstass** [comment]
Hello, @inokawa 

The link that u provided is dead. Where we can find example? 

Thanks.

**Comment by inokawa** [comment]
https://github.com/inokawa/virtua/blob/fbc41aa480f735aa5d7bda58d1f02fe1e96c45e9/stories/react/basics/Virtualizer.stories.tsx#L347

https://inokawa.github.io/virtua/?path=/story/basics-virtualizer--table-element

**Comment by inokawa** [comment]
#312
