### ISSUE TITLE
Support animation libraries officially

### ISSUE THREAD

**Issue by inokawa** [inokawa/virtua#76]

**Comment by morajabi** [comment]
@inokawa Can we support framer-motion for exit animation of visible items? Use-case: Animate deleting chat messages

**Comment by inokawa** [comment]
I tried it before but not succeeded yet.

One difficult point is enter/exit detectors like AnimatePresence of framer-motion can't understand which the mount/unmount is caused by virtualization or actual adding/removing.
It may be possible by keeping some state outside of virtual scroller.

**Comment by inokawa** [comment]
An example with auto-animate was added. It may be possible to use flamer in a similar way.

**Comment by Turbocat6413** [comment]
What do you think about the enter and exit animations in Svelte?
